os:
    - Visual Studio 2015
environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: c:\Libraries\boost_1_59_0\lib32-msvc-14.0
clone_folder: C:\amgcl
platform:
    - x86
configuration:
    - Release
build_script:
    - cmake .
    - cmake --build . --config Release
test_script:
    - ctest --build-config Release --output-on-failure
