language: cpp
compiler:
- clang

env:
  global:
      - secure: "Hl9sa1V5YSJDYOSr9wnw109Vvm27FVTIZC5gIEiNOwdsqdzsO2JTtnk/tLmhStUvyPfJ5Vv8lxc52KFBV1DNDLIT88hxdZ8yRdg1FClVY+B30IfSjO9nKfgNtpGBozBJOfUbOZJwMxsGOdjGDq0dn667E8WcljBLeywRyxjRFvY="

addons:
  coverity_scan:
    project:
      name: "ddemidov/amgcl"
      description: "Build submitted via Travis CI"
    notification_email: dennis.demidov@gmail.com
    build_command_prepend: mkdir build-coverity && cd build-coverity && cmake ..
    build_command: make
    branch_pattern: coverity-scan

before_install:
- sudo add-apt-repository ppa:boost-latest/ppa -y
- sudo apt-get update -qq
- sudo apt-get install -qq libboost-chrono1.55-dev libboost-date-time1.55-dev libboost-system1.55-dev
  libboost-filesystem1.55-dev libboost-program-options1.55-dev libboost-python1.55-dev
  libboost-test1.55-dev python-yaml lcov openmpi-bin libopenmpi-dev python-numpy-dev
  python-scipy
script:
- mkdir -p build && cd build
- cmake -DTEST_COVERAGE=ON ..
- make
- ctest --output-on-failure
- for n in 1 4 16; do echo --- $n ---; mpirun -np $n ./examples/mpi/runtime_sdd; done
after_success:
- lcov --directory tests --base-directory ../amgcl --capture --output-file coverage.info
- lcov --remove coverage.info '/usr*' -o coverage.info
- bash <(curl -s https://codecov.io/bash)
